name: 🏭 Build

on:
  push:
    branches: [ main ]
    paths: 
      - 'DateOnlyTimeOnly.AspNet/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'DateOnlyTimeOnly.AspNet/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 🧰 Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: 🏭 Build
      run: dotnet build --no-restore
