name: Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: DateOnlyTimeOnly.AspNet/DateOnlyTimeOnly.AspNet.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
