name: 🚀 Publish base package

on:
  push:
    branches: [ main ]
    paths: 
      - 'DateOnlyTimeOnly.AspNet/**'
      - '.github/workflows/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 🧰 Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    - name: 🚀 Publish NuGet
      uses: alirezanet/publish-nuget@v3.0.0
      with:
        PROJECT_FILE_PATH: DateOnlyTimeOnly.AspNet/DateOnlyTimeOnly.AspNet.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
