name: 🚀 Publish Swashbuckle package

on:
  push:
    branches: [ main ]
    paths: 
      - 'DateOnlyTimeOnly.AspNet.Swashbuckle/**'
      - '.github/workflows/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 🚀 Publish NuGet
      uses: alirezanet/publish-nuget@v3.0.0
      with:
        PROJECT_FILE_PATH: DateOnlyTimeOnly.AspNet.Swashbuckle/DateOnlyTimeOnly.AspNet.Swashbuckle.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
        TAG_FORMAT: Swashbuckle_v*
